In [15]:

import pandas as pd
import os

from src.data_loader import DataLoader
from src.preprocess import Preprocessor
from src.data_saver import DataSaver

In [16]:
data_loader = DataLoader(path="../data/raw/restaurant_dataset.csv")

In [17]:
data_loader.load()

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,...,currency,has_table_booking,has_online_delivery,is_delivering_now,switch_to_order_menu,price_range,aggregate_rating,rating_color,rating_text,votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [18]:
x_train, x_test, y_train, y_test = data_loader.split(target_column="aggregate_rating", to_drop=["restaurant_id", "votes", "rating_color", "rating_text"])

In [19]:
prep = Preprocessor()

In [20]:
x_train_filled, x_test_filled = prep.apply_fillna_train_to_test(x_train, x_test)

/Users/plosx/Desktop/machine-learning/modular_programming/project_2/src/preprocess.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(self.fill_values[col], inplace=True)
/Users/plosx/Desktop/machine-learning/modular_programming/project_2/src/preprocess.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(self.fill_values[col], inplace=True)
/Users/plosx/Desktop/machine-learning/modular_programming/project_2/src/preprocess.py:37: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(value, inplace=True)

In [21]:
x_train_filled.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7640 entries, 1115 to 7270
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   restaurant_name       7640 non-null   object
 1   country_code          7640 non-null   int64
 2   city                  7640 non-null   object
 3   address               7640 non-null   object
 4   locality              7640 non-null   object
 5   locality_verbose      7640 non-null   object
 6   longitude             7640 non-null   float64
 7   latitude              7640 non-null   float64
 8   cuisines              7640 non-null   object
 9   average_cost_for_two  7640 non-null   int64
 10  currency              7640 non-null   object
 11  has_table_booking     7640 non-null   object
 12  has_online_delivery   7640 non-null   object
 13  is_delivering_now     7640 non-null   object
 14  switch_to_order_menu  7640 non-null   object
 15  price_range           7640 non-null   int64
dtypes: float64(2), int64(3), object(11)
memory usage: 1014.7+ KB

In [22]:
x_train_encoded, x_test_encoded = prep.apply_encode_train_to_test(x_train_filled, x_test_filled)

In [23]:
x_train_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7640 entries, 1115 to 7270
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   restaurant_name       7640 non-null   int64
 1   country_code          7640 non-null   int64
 2   city                  7640 non-null   int64
 3   address               7640 non-null   int64
 4   locality              7640 non-null   int64
 5   locality_verbose      7640 non-null   int64
 6   longitude             7640 non-null   float64
 7   latitude              7640 non-null   float64
 8   cuisines              7640 non-null   int64
 9   average_cost_for_two  7640 non-null   int64
 10  currency              7640 non-null   int64
 11  has_table_booking     7640 non-null   int64
 12  has_online_delivery   7640 non-null   int64
 13  is_delivering_now     7640 non-null   int64
 14  switch_to_order_menu  7640 non-null   int64
 15  price_range           7640 non-null   int64
dtypes: float64(2), int64(14)
memory usage: 1014.7 KB

In [24]:
x_test_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1911 entries, 4731 to 180
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   restaurant_name       1911 non-null   int64
 1   country_code          1911 non-null   int64
 2   city                  1911 non-null   int64
 3   address               1911 non-null   int64
 4   locality              1911 non-null   int64
 5   locality_verbose      1911 non-null   int64
 6   longitude             1911 non-null   float64
 7   latitude              1911 non-null   float64
 8   cuisines              1911 non-null   int64
 9   average_cost_for_two  1911 non-null   int64
 10  currency              1911 non-null   int64
 11  has_table_booking     1911 non-null   int64
 12  has_online_delivery   1911 non-null   int64
 13  is_delivering_now     1911 non-null   int64
 14  switch_to_order_menu  1911 non-null   int64
 15  price_range           1911 non-null   int64
dtypes: float64(2), int64(14)
memory usage: 253.8 KB

In [25]:
x_train_scaled, x_test_scaled = prep.apply_scale_train_to_test(x_train_encoded, x_test_encoded)

In [26]:
x_train_scaled.head()

,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,average_cost_for_two,currency,has_table_booking,has_online_delivery,is_delivering_now,switch_to_order_menu,price_range
1115,1.700114,-0.305017,-1.467189,1.671179,1.535114,1.569181,0.319323,0.238361,0.817560,0.047166,0.02305,2.673011,-0.586621,-0.061727,0.0,1.315988
7633,-0.514509,-0.305017,0.410097,0.936564,1.477917,1.514779,0.312927,0.251822,-0.298878,-0.071644,0.02305,-0.374110,-0.586621,-0.061727,0.0,-0.892987
8267,0.266482,-0.305017,0.458233,-0.547627,0.745071,0.695340,0.321265,0.243827,0.527516,-0.071644,0.02305,-0.374110,-0.586621,-0.061727,0.0,-0.892987
7209,-1.324724,-0.305017,0.410097,0.996897,1.020335,1.072758,0.318753,0.252859,-0.386352,-0.061743,0.02305,-0.374110,-0.586621,-0.061727,0.0,-0.892987
6242,-1.040518,-0.305017,0.410097,-1.352711,0.419759,0.375725,0.315229,0.257864,1.024734,-0.038641,0.02305,-0.374110,-0.586621,-0.061727,0.0,0.211501

In [27]:
saver = DataSaver(base_path="..", version="baseline")

In [28]:
saver.save_files(
    x_train=x_train_scaled,
    x_test=x_test_scaled,
    y_train=y_train,
    y_test=y_test
)